name: Show commit message
on:
    push:
        branches:
            - main
            - mastesr
jobs:
    print-message:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Print Commit message
              run: |
                echo "Commit Message"
                echo "${{ github.event.head_commit.message }}"